---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/lpp/IBM/izoda/anaconda/bin/python3
    tgt_tmp_dir: /tmp
    ctl_tmp_dir: /tmp
  gather_facts: false
  environment:
    ZOAU_HOME: /usr/lpp/IBM/zoautil
    PATH: /usr/lpp/IBM/zoautil/bin:/usr/lpp/IBM/izoda/anaconda/bin:/bin
    LIBPATH: /usr/lpp/IBM/zoautil/lib:/usr/lpp/IBM/izoda/anaconda/lib:/lib:/usr/lib:.
    PYTHONPATH: /usr/lpp/IBM/zoautil/lib
    _BPXK_AUTOCVT: "ON"
  collections:
    - ibm.ibm_zos_core
  tasks:
    - name: Execute Build on a remote server
      ansible.builtin.command: sh /u/RGOPALK/runbuild.sh
      register: command_result
    - name: Command Result Output
      ansible.builtin.debug:
        msg: "{{ command_result }}"
    - name: Check for Build state
      ansible.builtin.fail:
        msg: Build Failed
      when: "'** Build State : ERROR' in command_result.stdout"
